### ISSUE TITLE
GPS retrieving data properly

### ISSUE THREAD

**Issue by Ethan144** [uOstar/barista#13]
The GPS itself is setup with the standard TX to RX and power/ground.
When reading, setup a serial with UART. The GPS will then return NMEA sentences. Specifically it will return 4 sentences in the format:

GPGGA,...
GPGSA,...
GPRMC,... 
GPYTG,...

This should then be parsed for the GPGGA and GPRMC strings as these 2 strings will be the ones to hold longitude, latitude, angle etc... separated by commas
ex: GPGGA,145240,000,3051.7773,N,10035.7586,W,1,6,1.30,359.4,M,-22.2,M, ,*60
145240 -> time, 3051.7773,N -> latitude using degree minutes, 10035.7586,W -> longitude
Will be updated with what everything else means.

useful links
setup: http://www.toptechboy.com/tutorial/beaglebone-black-gps-lesson-1-hooking-up-the-adafruit-ultimate-gps/
NMEA: http://www.toptechboy.com/arduino/lesson-24-understanding-gps-nmea-sentences/

**Comment by Ethan144** [comment]
Don't want to destroy any work by pushing without being 100% on how git works
[gps.txt](https://github.com/uOstar/barista/files/1494678/gps.txt)

**Comment by NikhilPeri** [comment]
we have a working GPS it just needs some tests in the real world
